In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5],dtype=float)
print(arr)

[1. 2. 3. 4. 5.]


In [ ]:

arr=np.arange(0,100,5)
print(arr)
data=np.savetxt("/content/arr.txt",arr)


[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [ ]:
import numpy as np
zeros_arr=np.zeros((3,3), dtype=int)
print(zeros_arr)
ones_arr=np.ones((2,2), dtype=int)
print(ones_arr)

arrange_arr=np.arange(10)
print(arrange_arr)
#array manipulation
reshaped_arr=arr.reshape(5,1)
print(reshaped_arr)
sliced_arr=arr[2:4]
print(sliced_arr)
a=np.array([1,2,3,4,5,6,7,8])
b=a.T
print(b)
b=np.split(a,4)
print(b)

In [ ]:

a=np.random.rand()
print(a)
b=np.random.randint(0,2)
print(b)
c=np.array([[1,2],[3,4]])
print(c.max(axis=0))#coloum
print(c.ndim)
print(c.shape)


0.34832360217761626
0
[3 4]
2
(2, 2)


In [ ]:
a=np.linspace(0.8,2,5)
print(a)
b=np.arange(24).reshape(3,2,4)
print(b)

In [ ]:
from numpy import random
a=np.ones((2,3),dtype=int)
print(a.max(axis=0))
print(a.sum(axis=1))
print(a.sum(axis=0))


[1 1 1]
[3 3]
[2 2 2]


In [ ]:
a=np.ceil(np.random.random((2,12)))
print(a)
c=np.random.random((2,2))
print(c)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[0.06423575 0.46996739]
 [0.68472204 0.25818609]]


In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[1,2],[3,4]])

print(a.cumsum(axis=1))
print(np.dot(a,b))
print(a@(b))
print(a*b)

[[1 3]
 [3 7]]
[[ 7 10]
 [15 22]]
[[ 7 10]
 [15 22]]
[[ 1  4]
 [ 9 16]]


In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=np.dot(a,b)
print(c)
d=np.linalg.eig(c)
print(d)


In [ ]:
import numpy as np
data=np.loadtxt("/content/drive/MyDrive/dataset/sample.txt",dtype=int)
d=np.savetxt("/content/drive/MyDrive/dataset/sample.txt",data)
print(d)
print(data)

In [ ]:
a=np.array([2,3,5,6,7,8])
print(a)
print(a.resize(3,2))
print(a.shape)
print(a.cumsum())

[2 3 5 6 7 8]
None
(3, 2)
[ 2  5 10 16 23 31]


In [ ]:
a=np.array([2,3,5,6,7,8])
print(a.resize(2,3))
b=np.array([9,10,1,2,3,4])
print(b.resize(2,3))
print(np.vstack((a,b)))
print(np.hstack((a,b)))

None
None
[[ 2  3  5]
 [ 6  7  8]
 [ 9 10  1]
 [ 2  3  4]]
[[ 2  3  5  9 10  1]
 [ 6  7  8  2  3  4]]


In [ ]:
b=np.arange(30).reshape(2,3,5)
print(b)
print(np.dstack(b))

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
[[[ 0 15]
  [ 1 16]
  [ 2 17]
  [ 3 18]
  [ 4 19]]

 [[ 5 20]
  [ 6 21]
  [ 7 22]
  [ 8 23]
  [ 9 24]]

 [[10 25]
  [11 26]
  [12 27]
  [13 28]
  [14 29]]]


no.of rows become group
colomn become rows
group become column